server:
  port: 8761 #porta padrão do eureka server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # o eureka não vai se registrar no proprio servidor eureka
    fetchRegistry: false #não vai guardar inf de outras aplicacoes
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# up: http://localhost:8761/